<pre class="metadata">
Title: Close Watcher API
Shortname: close-watcher
Repository: domenic/close-watcher
Inline Github Issues: true
Status: DREAM
URL: https://domenic.github.io/close-watcher/
Boilerplate: omit conformance, omit feedback-header
Metadata Include: This version off
Editor: Domenic Denicola, Google https://www.google.com/, d@domenic.me, https://domenic.me/
Abstract: The close watcher API provides a platform-agnostic way of handling close signals.
!Participate: <a href="https://github.com/domenic/close-watcher">GitHub domenic/close-watcher</a> (<a href="https://github.com/domenic/close-watcher/issues/new">new issue</a>, <a href="https://github.com/domenic/close-watcher/issues?state=open">open issues</a>)
!Commits: <a href="https://github.com/WICG/app-history/commits/master/spec.bs">GitHub spec.bs commits</a>
Complain About: accidental-2119 yes, missing-example-ids yes
Indent: 2
Default Biblio Status: current
Markup Shorthands: markdown yes
Assume Explicit For: yes
</pre>
